-- Email List — Supabase/Postgres schema
--
-- Run this once in the Supabase SQL editor (Project → SQL Editor → New query)
-- before running `npm run migrate`, and before pointing the app at Supabase.
--
-- Every statement here is safe to re-run: tables/indexes use IF NOT EXISTS,
-- so running this twice (e.g. if you're not sure it worked the first time)
-- won't error or duplicate anything.

-- ============================================================
-- Core tables (contacts, segments, campaigns) — same shape as
-- the original SQLite schema, translated to Postgres types.
-- ============================================================

create table if not exists contacts (
  id bigint generated by default as identity primary key,
  name text,
  email text not null,
  status text not null default 'active' check (status in ('active', 'unsubscribed')),
  unsubscribe_token text not null,
  created_at timestamptz not null default now()
);
create unique index if not exists idx_contacts_email on contacts (lower(email));
create unique index if not exists idx_contacts_unsubscribe_token on contacts (unsubscribe_token);
create index if not exists idx_contacts_status on contacts (status);

create table if not exists segments (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamptz not null default now()
);
create unique index if not exists idx_segments_name on segments (lower(name));

create table if not exists contact_segments (
  contact_id bigint not null references contacts(id) on delete cascade,
  segment_id bigint not null references segments(id) on delete cascade,
  primary key (contact_id, segment_id)
);
create index if not exists idx_contact_segments_segment on contact_segments (segment_id);
create index if not exists idx_contact_segments_contact on contact_segments (contact_id);

create table if not exists campaigns (
  id bigint generated by default as identity primary key,
  subject text not null,
  sender_name text,
  body_html text not null,
  recipient_count integer not null default 0,  -- successful sends (Resend accepted)
  failed_count integer not null default 0,     -- Resend rejected the send attempt
  status text not null default 'sent',         -- 'sent' | 'partial' | 'failed'
  recipient_mode text default 'all',           -- 'all' | 'segments'
  excluded_unsubscribed integer default 0,
  sent_at timestamptz not null default now()
);
create index if not exists idx_campaigns_sent_at on campaigns (sent_at desc);

-- Snapshot of which segments a campaign targeted at send time. Kept
-- separate from live segment membership on purpose — a contact moving
-- segments later must never rewrite history (see campaign_recipients below
-- for the same reasoning applied to who received the campaign).
create table if not exists campaign_segments (
  campaign_id bigint not null references campaigns(id) on delete cascade,
  segment_id bigint,           -- kept for convenience; not FK-enforced so a
                                -- later segment deletion doesn't touch history
  segment_name text not null,  -- what's actually displayed — accurate even
                                -- if the segment is renamed or deleted later
  primary key (campaign_id, segment_name)
);

-- ============================================================
-- New: per-recipient send records and the event log they're
-- built from. This is what makes "who opened/clicked what"
-- answerable, instead of only campaign-wide totals.
-- ============================================================

-- One row per contact per campaign they were sent to. This is the
-- historical record of *who* a campaign went to — independent of that
-- contact's segment membership today. Timestamp columns are a fast-read
-- cache kept in sync from email_events (the source of truth); if the two
-- ever disagree, trust email_events.
create table if not exists campaign_recipients (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references campaigns(id) on delete cascade,
  contact_id bigint references contacts(id) on delete set null,
  email text not null,               -- snapshot, so history survives a contact being deleted
  provider_message_id text,          -- Resend's email id for this specific send
  status text not null default 'pending',  -- pending|sent|failed|delivered|opened|clicked|bounced|complained|delivery_delayed
  error text,                        -- Resend's error message, if the send failed
  sent_at timestamptz,
  delivered_at timestamptz,
  opened_at timestamptz,
  clicked_at timestamptz,
  bounced_at timestamptz,
  complained_at timestamptz,
  delayed_at timestamptz,
  unsubscribed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (campaign_id, contact_id)
);
create index if not exists idx_campaign_recipients_campaign on campaign_recipients (campaign_id);
create index if not exists idx_campaign_recipients_contact on campaign_recipients (contact_id);
-- A given Resend message id belongs to exactly one recipient, and is how
-- incoming webhook events get matched back to a campaign + contact.
create unique index if not exists idx_campaign_recipients_message_id
  on campaign_recipients (provider_message_id) where provider_message_id is not null;

-- Append-only log of every delivery/engagement event, whether it came from
-- a Resend webhook (delivered, opened, clicked, bounced, complained,
-- delivery_delayed) or was recorded directly by this app (sent, at send
-- time; unsubscribed, from our own /unsubscribe link). This table is the
-- source of truth for analytics — campaign_recipients' *_at columns are a
-- convenience cache derived from it.
create table if not exists email_events (
  id bigint generated by default as identity primary key,
  campaign_id bigint references campaigns(id) on delete cascade,
  contact_id bigint references contacts(id) on delete set null,
  campaign_recipient_id bigint references campaign_recipients(id) on delete cascade,
  provider_message_id text,
  event_type text not null check (event_type in (
    'sent', 'delivered', 'delivery_delayed', 'bounced', 'complained',
    'opened', 'clicked', 'unsubscribed', 'failed'
  )),
  provider_event_id text,  -- Resend/Svix's svix-id header - stable across
                            -- webhook redelivery, so this is our dedup key
  link_url text,           -- populated for 'clicked' events
  metadata jsonb,          -- raw extra detail (bounce reason, user agent, etc)
  occurred_at timestamptz not null default now(),  -- when Resend says it happened
  created_at timestamptz not null default now()    -- when we stored it
);
create index if not exists idx_email_events_campaign on email_events (campaign_id);
create index if not exists idx_email_events_contact on email_events (contact_id);
create index if not exists idx_email_events_message_id on email_events (provider_message_id);
create index if not exists idx_email_events_type on email_events (event_type);
create index if not exists idx_email_events_created_at on email_events (created_at desc);
-- Idempotency: Resend delivers webhooks at-least-once and redelivers the
-- *same* svix-id on retry, so this makes a duplicate delivery a no-op
-- instead of double-counting an open/click/bounce/etc.
create unique index if not exists idx_email_events_provider_event_id
  on email_events (provider_event_id) where provider_event_id is not null;

-- ============================================================
-- Done. Next: run `npm run migrate` to copy your existing SQLite
-- data into these tables (see README.md → "How to migrate").
-- ============================================================
